Fix GetEmoteSets method missing OwnerID in emote response
nicklaw5/helix pull request #100
Opened 2021-06-27 12:37 UTC by pajlada

- `GetEmoteSets` now returns a `GetEmoteSetsResponse` instead of `GetChannelEmotesResponse`
- Ensure emotes are marshalled properly in `TestGetEmoteSets`

There's still a few ways you could chose to do the emote type - I went with a "parent" type EmoteWithOwner - let me know if you have another preference.

Unrelated to the PR but I noteiced while working on this - The naming of the `Set_ID` parameter seems out of place among all the other members. Would love to see that changed to `SetID` but I'll create an issue for it instead of rambling on in this PR.

2021-06-27 12:58 UTC, zneix requested changes

2021-06-27 12:58 UTC, zneix commented on chat_test.go
> +							Url4x: "https://static-cdn.jtvnw.net/emoticons/v1//3.0",
No idea why is there no emote ID here. Would have to adjust JSON in line 335 as well.

```suggestion
							Url4x: "https://static-cdn.jtvnw.net/emoticons/v1/301147694/3.0",
```

2021-06-27 18:35 UTC, nicklaw5 commented
Looks good. Can you please resolve @zneix's suggested change? Then I'm happy to merge.

2021-06-27 18:52 UTC, nicklaw5 commented
I've created #101 to resolve the `Set_ID` struct field.

2021-06-28 01:55 UTC, zneix approved these changes

2021-06-28 06:05 UTC, nicklaw5 approved these changes

2021-06-28 06:06 UTC, merged