Add GetStreamKey
nicklaw5/helix pull request #135
Opened 2022-03-23 12:25 UTC by kivutar

2022-03-23 20:16 UTC, nicklaw5 requested changes
Thanks for the PR @kivutar. Can you please review the comments I've left?

Also, we'll need some tests for this endpoint before I can merge.

2022-03-23 20:16 UTC, nicklaw5 commented on streams.go
> +	streams.Data.Streams = resp.Data.(*ManyStreams).Streams
`ManyStreams` is not a correct representation of the response object for this endpoint. The response, according to the [docs](https://dev.twitch.tv/docs/api/reference#get-stream-key), should only in the `stream_key` property.

```json
{
  "data": [
    {
      "stream_key": "live_44322889_a34ub37c8ajv98a0"
    },
  ]
}
```

My suggestion would be to create a new struct called `ManyStreamKeys` instead. For example:

```go
type ManyStreamKeys struct {
    Data []struct{
        StreamKey string `json:"stream_key"`
    } `json:"data"`
}
```

2022-03-23 20:16 UTC, nicklaw5 commented on streams.go
> +	streams.Data.Pagination = resp.Data.(*ManyStreams).Pagination
There's also no pagination for this endpoint according to the [docs](https://dev.twitch.tv/docs/api/reference#get-stream-key).

2022-04-05 08:35 UTC, kivutar commented
@nicklaw5 this should be fine now

2022-04-05 20:23 UTC, nicklaw5 approved these changes
Good enough for me :+1:

(Sorry for the delay)

2022-04-05 20:24 UTC, merged