add ban/unban user
nicklaw5/helix pull request #146
Opened 2022-10-15 15:28 UTC by diPhantxm

- add ban/unban endpoints
- unit tests

2022-10-16 19:59 UTC, nicklaw5 requested changes
Thanks for contributing. Looks good. We just need to adjust the time field types. See the comments I've left.

2022-10-16 19:59 UTC, nicklaw5 commented on moderation.go
> +	EndTime       string `json:"end_time"`
Both `CreatedAt` and `EndTime` fields should be of type [Time](https://github.com/nicklaw5/helix/blob/main/time.go#L17-L19). This allows the our custom [UnmarshalJSON](https://github.com/nicklaw5/helix/blob/main/time.go#L26-L37) to handle converting the string represented time to a native [time.Time](https://pkg.go.dev/time#Time) type.

See the [User type](https://github.com/nicklaw5/helix/blob/main/users.go#L16) as an example.

2022-10-16 19:59 UTC, nicklaw5 commented on moderation_test.go
> +				endTime, _ := time.Parse(layout, resp.Data.Bans[0].EndTime)
By actioning the above comment, you won't need to perform `time.Parse` here. The parsing occur when the JSON unmarshaling happens. These three lines can be removed.

2022-10-16 19:59 UTC, nicklaw5 commented on moderation_test.go
> +				}
These lines can then be written like so:

```suggestion
				expireTime := resp.Data.Bans[0].CreatedAt.Add(time.Duration(testCase.params.Body.Duration * int(time.Second)))

				if !expireTime.Equal(resp.Data.Bans[0].EndTime) {
					t.Errorf("expected endtime to be \"%s\", got \"%s\"", expireTime, resp.Data.Bans[0].EndTime)
				}
```

2022-10-17 19:49 UTC, diPhantxm commented
Thanks for your comment. I've fixed data types as you said. Also added comment to unban user function and noticed one more defect in test function.
Didn't notice your data type for time right away. It's actually my first time contributing to an open source project.

2022-10-17 19:54 UTC, nicklaw5 commented
Thanks and welcome to open source development :slightly_smiling_face:

2022-10-17 19:54 UTC, merged