Correcting scopes to pass as space-separated list
nicklaw5/helix pull request #65
Opened 2020-11-27 20:00 UTC by intel352

Correcting scopes to pass as space-separated list, rather than &scope…=...&scope=..., per the [documentation](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/). 

Without this change, the API only recognizes the first scope that is passed.

Existing tests are unaffected either way. The difference is that when scopes are actually being requested against a live twitch service, the scopes that are returned always only reflects the first one in the list.

2020-11-27 23:23 UTC, nicklaw5 requested changes

2020-11-27 23:23 UTC, nicklaw5 commented on authentication.go
> +	Scopes       string `query:"scope"`
`Scopes` throughout this project are a slice of strings. So let's revert this change and instead action the following comment.

2020-11-27 23:23 UTC, nicklaw5 commented on authentication.go
> +		Scopes:       strings.Join(scopes, " "),
I think I'd prefer the following:

```suggestion
		Scopes:       strings.Split(scopes, " "),
```

2020-11-28 00:01 UTC, nicklaw5 commented
I just realised I completely misunderstood the changes you've introduced. Please ignore my comments.

2020-11-28 00:04 UTC, nicklaw5 approved these changes

2020-11-28 00:04 UTC, merged

2020-11-28 00:23 UTC, intel352 commented
> I just realised I completely misunderstood the changes you've introduced. Please ignore my comments.

No worries, I actually debated even renaming the property to reduce confusion, as it's a bit misleading. Good thing IDEs tell us if it's wrong :)